engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
ratings:
  paths:
  - "taint_module/*"
  - "**.py"
exclude_paths:
- "taint_module/draw.py"
- "taint_module/github_search.py"
- "taint_module/intraprocedural_cfg.py"
- "taint_module/repo_runner.py"
- "taint_module/save.py"
- "examples/**"
- "profiling/**"
- "tests/**"
- "LICENSE"
- "**/trigger_definitions/*"
- "**.cfg"
- "**.csv"
- "**.in"
- "**.md"
- "**.png"
- "**.taint_module"
- "**.rst"
- "**.sh"
- "**.txt"
